providers = ["python", "node"]

[variables]
NIXPACKS_NODE_VERSION = "22"

[phases.build]
cmds = [
    "cd frontend_v2 && rm -rf package-lock.json node_modules && npx pnpm install && npx pnpm run build",
    "pip install -r requirements.txt --no-cache-dir"
]

[start]
cmd = "uvicorn backend.main:app --host 0.0.0.0 --port $PORT"
